#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

python3 scripts/sync_hermes_config.py

git add -A

if git diff --cached --quiet; then
  echo "No changes to commit."
  exit 0
fi

summary="$(git diff --cached --stat)"
files="$(git diff --cached --name-only | sed 's/^/- /')"

git commit -m "chore(hermes-config): sync tracked Hermes configuration snapshot" -m "Summary:
$summary

Files:
$files

Generated by scripts/commit_and_push.sh after syncing from /home/liuli/.hermes." 
GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=accept-new -p 443' git push origin HEAD

echo "Committed and pushed Hermes config snapshot."
