#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="/home/liuli/.hermes/hermes-agent"
cd "$REPO_DIR"

git add -A

if git diff --cached --quiet; then
  echo "No Hermes agent code changes to commit."
  exit 0
fi

summary="$(git diff --cached --stat)"
files="$(git diff --cached --name-only | sed 's/^/- /')"

msg_subject="chore(hermes-agent): sync local Hermes agent changes"
msg_body="Summary:
$summary

Files:
$files

Auto-generated by /home/liuli/agent-configs/hermes-config/scripts/commit_hermes_agent_code.sh."

git commit -m "$msg_subject" -m "$msg_body"
GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=accept-new -p 443' git push origin HEAD

echo "Committed and pushed Hermes agent code changes."
